import "./globals.css";

import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Nexora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col justify-between nexora-container">
        <header className="flex justify-between mt-7">
          <h1 className="font-bold font-[Silkscreen] text-xl">nexora</h1>
          <Navbar />
        </header>

        <div className="nexora-container w-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
