import "./globals.css";

import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Link from "next/link";

export const metadata = {
  title: "Nexora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col justify-between nexora-container">
        <header className="mt-4 md:flex md:justify-between">
          <Link href="/" className="font-bold font-[Silkscreen] text-xl p-3">
            nexora
          </Link>
          <Navbar />
        </header>

        <div className="w-full text-center">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
